# Generated by Django 5.0.2 on 2024-02-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Technology', 'Information and Technology'), ('Movies', 'Movies'), ('Country', 'Countries'), ('Culture', 'Cultural'), ('Entertainment', 'Entertainment and videos'), ('Education', 'Education and Learning'), ('Sports', 'Sports and Fitness'), ('Travel', 'Travel and Adventure'), ('Other', 'Other')], max_length=255, unique=True),
        ),
    ]
