# Generated by Django 5.0.2 on 2024-02-23 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default=datetime.datetime(2024, 2, 23, 4, 25, 48, 240280, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'USER')], default=datetime.datetime(2024, 2, 23, 4, 26, 1, 589884, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Technology', 'Information and Technology'), ('Movies', 'Movies'), ('Country', 'Countries'), ('Culture', 'Cultural'), ('Entertainment', 'Entertainment and videos'), ('Education', 'Education and Learning'), ('Sports', 'Sports and Fitness'), ('Travel', 'Travel and Adventure'), ('Other', 'Other')], max_length=150, unique=True),
        ),
    ]
