# Generated by Django 5.0.2 on 2024-02-23 06:10

import blog_app.util.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_author_password_author_role_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(db_index=True, default=blog_app.util.util.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(db_index=True, default=blog_app.util.util.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(db_index=True, default=blog_app.util.util.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(db_index=True, default=blog_app.util.util.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
