# Generated by Django 5.0.2 on 2024-02-28 05:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_author_id_alter_category_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='otp',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='otp_sent_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 28, 5, 16, 15, 216229, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
