# Generated by Django 5.0.2 on 2024-02-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_author_is_verified_author_otp_author_otp_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='otp_sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
