# Generated by Django 5.0.2 on 2024-02-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_alter_author_otp_alter_author_otp_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='otp_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
