# Generated by Django 5.0.2 on 2024-02-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_forgetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog_app.author'),
        ),
    ]
