# Generated by Django 5.0.2 on 2024-02-28 12:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_alter_forgetpassword_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2024, 2, 28, 12, 7, 56, 619748, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='blog_app.author'),
            preserve_default=False,
        ),
    ]
