# Generated by Django 5.0.2 on 2024-03-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
